import { Activity, AlertTriangle, Ambulance, ArrowRight, Check, ChevronRight, ClipboardList, Clock3, Droplets, HeartPulse, Hospital, MapPin, PhoneCall, Pill, RotateCcw, ShieldAlert, Thermometer, Wind } from 'lucide-react';
import { demoHospitals, demoPatient, localize, type Lang, type PrototypeCopy } from '@/lib/prototype-i18n';

type Props = { lang: Lang; t: PrototypeCopy; stage: number; selectedHospital: string };
type DashboardProps = Props & { onStart: () => void; onContinue: () => void; onRecord: () => void; onTracker: () => void; onReset: () => void };
const panel = 'rounded-2xl border border-[hsl(var(--card-border))] bg-[hsl(var(--card))] shadow-[0_12px_34px_hsl(211_49%_18%/.055)]';
const primaryButton = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-5 py-3 text-sm font-extrabold text-white hover:opacity-90';

export function DemoNotice({ t }: { t: PrototypeCopy }) {
  return <div className="flex items-start gap-3 rounded-xl border border-[hsl(var(--primary)/.22)] bg-[hsl(var(--primary)/.07)] px-4 py-3 text-xs leading-relaxed text-[hsl(var(--foreground))]" role="note"><ShieldAlert size={17} className="mt-0.5 shrink-0 text-[hsl(var(--primary))]" /><span><strong className="me-2 text-[hsl(var(--primary))]">{t.ops.demo}</strong>{t.ops.notice}</span></div>;
}

export function EmergencyCall({ t }: { t: PrototypeCopy }) {
  return <section className={`${panel} overflow-hidden border-[hsl(var(--destructive)/.25)]`} aria-label={t.ops.callTitle}>
    <div className="flex flex-col gap-5 bg-[hsl(var(--destructive)/.055)] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6">
      <div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[hsl(var(--destructive)/.12)] text-[hsl(var(--destructive))]"><PhoneCall size={21} /></span><div><h2 className="font-extrabold">{t.ops.callTitle}</h2><p className="mt-1 max-w-xl text-xs leading-relaxed text-[hsl(var(--muted-foreground))]">{t.ops.callCopy}</p></div></div>
      <a data-testid="link-call-emergency" href="tel:997" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-[hsl(var(--destructive))] px-6 text-sm font-extrabold text-white hover:opacity-90"><PhoneCall size={17} />{t.ops.callAction}</a>
    </div><div className="border-t border-[hsl(var(--destructive)/.12)] px-5 py-3 text-[11px] text-[hsl(var(--muted-foreground))]">{t.ops.callNote}</div>
  </section>;
}

export function TransportTracker({ lang, t, stage, selectedHospital, onArrival, compact = false }: Props & { onArrival?: () => void; compact?: boolean }) {
  const destination = demoHospitals.find((h) => h.id === selectedHospital) ?? demoHospitals[0];
  const labels = [t.ops.stageIdentify, t.ops.stageRecord, t.ops.stageDestination, t.ops.stageHandoff, t.ops.stageArrival];
  return <section className={`${panel} overflow-hidden`} data-testid="section-transport-tracker">
    <div className="flex flex-wrap items-start justify-between gap-3 border-b border-[hsl(var(--border))] p-5"><div><div className="flex items-center gap-2 font-extrabold"><MapPin size={18} className="text-[hsl(var(--primary))]" />{t.ops.trackerTitle}</div><p className="mt-1 text-xs leading-relaxed text-[hsl(var(--muted-foreground))]">{t.ops.trackerSubtitle}</p></div><span data-testid="status-transport-stage" className="rounded-full bg-[hsl(var(--secondary))] px-3 py-1 text-xs font-bold text-[hsl(var(--primary))]">{stage >= 5 ? t.ops.arrived : labels[stage]}</span></div>
    <div className="p-5">
      <div className="grid grid-cols-5 gap-1" aria-label={t.ops.trackerTitle}>{labels.map((label, index) => <div key={label} className="min-w-0" data-testid={`status-transport-step-${index}`}><div className={`mb-2 grid h-8 w-8 place-items-center rounded-full text-xs font-bold ${index < stage ? 'bg-[hsl(var(--primary))] text-white' : index === stage ? 'border-2 border-[hsl(var(--primary))] text-[hsl(var(--primary))]' : 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]'}`}>{index < stage ? <Check size={15} /> : index + 1}</div><div className="border-t-2 border-[hsl(var(--border))] pt-2 text-[10px] font-bold leading-tight sm:text-xs">{label}</div></div>)}</div>
      {!compact && <div className="mt-6 grid gap-3 rounded-xl bg-[hsl(var(--muted)/.55)] p-4 text-xs sm:grid-cols-3"><div><div className="text-[hsl(var(--muted-foreground))]">{t.ops.ambulance}</div><strong className="mt-1 block font-mono">AMB-204</strong></div><div><div className="text-[hsl(var(--muted-foreground))]">{t.ops.destination}</div><strong className="mt-1 block">{stage >= 3 ? localize(destination.name, lang) : t.ops.etaUnknown}</strong></div><div><div className="text-[hsl(var(--muted-foreground))]">{t.ops.eta}</div><strong className="mt-1 block">{stage >= 5 ? t.ops.arrived : stage >= 3 ? `${destination.eta} ${t.common.minutes}` : t.ops.etaUnknown}</strong></div><div className="sm:col-span-3"><span className="text-[hsl(var(--muted-foreground))]">{t.ops.route}: </span>{t.ops.routeValue}</div></div>}
      {stage === 0 && <p className="mt-4 text-xs text-[hsl(var(--muted-foreground))]">{t.ops.noCase}</p>}
      {stage > 0 && stage < 4 && <p className="mt-4 text-xs text-[hsl(var(--muted-foreground))]">{t.ops.stageHint}</p>}
      {stage === 4 && onArrival && <button data-testid="button-mark-arrival" type="button" onClick={onArrival} className={`${primaryButton} mt-5 w-full sm:w-auto`}><Check size={16} />{t.ops.markArrival}</button>}
      {stage >= 5 && <p role="status" data-testid="status-arrival-feedback" className="mt-4 rounded-lg bg-[hsl(var(--primary)/.09)] p-3 text-xs text-[hsl(var(--primary))]">{t.ops.arrivalFeedback}</p>}
    </div>
  </section>;
}

export function ParamedicOperations({ lang, t, stage, selectedHospital, onStart, onContinue, onRecord, onTracker, onReset }: DashboardProps) {
  const next = stage === 0 ? onStart : onContinue;
  return <main className="mx-auto max-w-[1280px] space-y-5 px-5 py-8 md:px-9 md:py-10">
    <DemoNotice t={t} />
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[hsl(var(--primary))]">{t.app.paramedic} / {t.ops.demo}</div><h1 className="mt-2 text-3xl font-extrabold tracking-tight md:text-4xl">{t.ops.paramedicTitle}</h1><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{t.ops.paramedicSubtitle}</p></div><button data-testid="button-quick-start" type="button" onClick={next} className={primaryButton}>{stage === 0 ? t.ops.startCase : t.ops.continueCase}<ArrowRight size={16} className="rtl:rotate-180" /></button></div>
    <div className="grid gap-4 md:grid-cols-[1.15fr_.85fr]">
      <section className={`${panel} p-5 md:p-6`}><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-extrabold"><Ambulance size={18} className="text-[hsl(var(--primary))]" />{t.ops.activeCases}</h2><span className="font-mono text-2xl font-bold text-[hsl(var(--primary))]">{stage > 0 ? '01' : '00'}</span></div>{stage > 0 ? <div className="mt-5 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--muted)/.35)] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{localize(demoPatient.name, lang)}</strong><span className="rounded-full bg-[hsl(var(--destructive)/.1)] px-2 py-1 text-[11px] font-bold text-[hsl(var(--destructive))]">{t.common.critical}</span></div><p className="mt-1 font-mono text-xs text-[hsl(var(--muted-foreground))]">{demoPatient.patientId} · AMB-204</p><button data-testid="button-active-case" type="button" onClick={onContinue} className="mt-4 flex items-center gap-1 text-xs font-extrabold text-[hsl(var(--primary))]">{t.ops.continueCase}<ChevronRight size={14} className="rtl:rotate-180" /></button></div> : <p className="mt-6 text-sm text-[hsl(var(--muted-foreground))]">{t.ops.noActive}</p>}</section>
      <section className={`${panel} p-5 md:p-6`}><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-extrabold"><ClipboardList size={18} className="text-[hsl(var(--primary))]" />{t.ops.transfers}</h2><span className="font-mono text-2xl font-bold text-[hsl(var(--primary))]">{stage >= 4 ? '01' : '00'}</span></div><p className="mt-5 text-sm text-[hsl(var(--muted-foreground))]">{stage >= 4 ? t.ops.localHandoff : t.ops.noTransfers}</p>{stage >= 4 && <p className="mt-2 text-xs font-bold">{localize(demoHospitals.find((h) => h.id === selectedHospital)?.name ?? demoHospitals[0].name, lang)}</p>}</section>
    </div>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><TransportTracker lang={lang} t={t} stage={stage} selectedHospital={selectedHospital} compact /><div className="space-y-5"><section className={`${panel} p-5`}><h2 className="flex items-center gap-2 font-extrabold"><AlertTriangle size={18} className="text-[hsl(var(--destructive))]" />{t.ops.alerts}</h2><p className="mt-4 rounded-xl bg-[hsl(var(--destructive)/.07)] p-4 text-sm text-[hsl(var(--destructive))]">{t.ops.alertDetail}</p>{stage > 0 && <button data-testid="button-dashboard-record" type="button" onClick={onRecord} className="mt-4 text-xs font-extrabold text-[hsl(var(--primary))]">{t.ops.reviewRecord} <ChevronRight size={14} className="inline rtl:rotate-180" /></button>}</section><button data-testid="button-dashboard-tracker" type="button" onClick={onTracker} className={`${panel} flex w-full items-center justify-between p-5 text-start text-sm font-extrabold text-[hsl(var(--primary))] hover:bg-[hsl(var(--primary)/.06)]`}>{t.ops.openTracker}<ArrowRight size={16} className="rtl:rotate-180" /></button></div></div>
    <EmergencyCall t={t} />
    {stage > 0 && <button data-testid="button-reset-case" type="button" onClick={() => { if (window.confirm(t.ops.resetConfirm)) onReset(); }} className="flex items-center gap-2 text-xs font-bold text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--destructive))]"><RotateCcw size={14} />{t.ops.resetCase}</button>}
  </main>;
}

export function HospitalOperations({ lang, t, stage, selectedHospital, onOpen }: Props & { onOpen: () => void }) {
  const destination = demoHospitals.find((h) => h.id === selectedHospital) ?? demoHospitals[0];
  return <main className="mx-auto max-w-[1280px] space-y-5 px-5 py-8 md:px-9 md:py-10"><DemoNotice t={t} /><div><div className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[hsl(var(--primary))]">{t.app.hospital} / {t.ops.demo}</div><h1 className="mt-2 text-3xl font-extrabold tracking-tight md:text-4xl">{t.ops.hospitalTitle}</h1><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{t.ops.hospitalSubtitle}</p></div>
    <section className={`${panel} overflow-hidden`}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[hsl(var(--border))] p-5"><div><h2 className="flex items-center gap-2 font-extrabold"><Hospital size={18} className="text-[hsl(var(--primary))]" />{t.ops.caseQueue}</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{t.ops.caseQueueHint}</p></div><span className="font-mono text-xl font-bold text-[hsl(var(--primary))]">01</span></div><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-lg">{localize(demoPatient.name, lang)}</strong><span className="rounded-full bg-[hsl(var(--destructive)/.1)] px-2 py-1 text-[11px] font-bold text-[hsl(var(--destructive))]">{t.common.critical}</span></div><p className="mt-1 font-mono text-xs text-[hsl(var(--muted-foreground))]">{demoPatient.patientId} · AMB-204</p><p className="mt-3 text-xs text-[hsl(var(--muted-foreground))]">{t.ops.sample} · {stage >= 4 ? t.ops.localHandoff : t.ops.awaiting}</p></div><button data-testid="button-open-incoming-case" type="button" onClick={onOpen} className={primaryButton}>{t.ops.openCase}<ArrowRight size={16} className="rtl:rotate-180" /></button></div></section>
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><TransportTracker lang={lang} t={t} stage={stage} selectedHospital={selectedHospital} /><section className={`${panel} p-5`}><h2 className="flex items-center gap-2 font-extrabold"><Clock3 size={18} className="text-[hsl(var(--primary))]" />{t.ops.destination}</h2><p className="mt-5 text-xl font-extrabold">{stage >= 3 ? localize(destination.name, lang) : t.ops.etaUnknown}</p><p className="mt-3 text-xs text-[hsl(var(--muted-foreground))]">{t.ops.eta}: {stage >= 5 ? t.ops.arrived : stage >= 3 ? `${destination.eta} ${t.common.minutes}` : t.ops.etaUnknown}</p><p className="mt-5 border-t border-[hsl(var(--border))] pt-4 text-xs text-[hsl(var(--muted-foreground))]">{t.ops.routeValue}</p></section></div><EmergencyCall t={t} />
  </main>;
}

export function HospitalCaseDetail({ lang, t, stage, selectedHospital, checklist, onToggle, onBack }: Props & { checklist: boolean[]; onToggle: (index: number) => void; onBack: () => void }) {
  const destination = demoHospitals.find((h) => h.id === selectedHospital) ?? demoHospitals[0];
  const readiness = Math.round(checklist.filter(Boolean).length / checklist.length * 100);
  const vitals = [
    { icon: HeartPulse, label: t.record.heartRate, value: `${demoPatient.vitals.heartRate} bpm` },
    { icon: Activity, label: t.record.bloodPressure, value: `${demoPatient.vitals.bloodPressure} mmHg` },
    { icon: Droplets, label: t.record.oxygen, value: `${demoPatient.vitals.oxygen}%` },
    { icon: Wind, label: t.record.respiratory, value: `${demoPatient.vitals.respiratory}/min` },
    { icon: Thermometer, label: t.record.temperature, value: `${demoPatient.vitals.temperature}°C` },
    { icon: HeartPulse, label: t.record.consciousness, value: localize(demoPatient.vitals.consciousness, lang) },
  ];
  return <main className="mx-auto max-w-[1480px] space-y-5 px-5 py-7 md:px-9">
    <button data-testid="button-back-hospital-dashboard" type="button" onClick={onBack} className="flex items-center gap-2 text-xs font-bold text-[hsl(var(--primary))]"><ArrowRight size={15} className="rotate-180 rtl:rotate-0" />{t.ops.backDashboard}</button>
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[hsl(var(--primary))]">{t.ops.sample}</div><h1 className="mt-2 text-3xl font-extrabold">{t.hospital.title}</h1><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{t.hospital.subtitle}</p></div><span data-testid="status-hospital-case" className="self-start rounded-full bg-[hsl(var(--primary)/.12)] px-3 py-1 text-xs font-bold text-[hsl(var(--primary))]">{stage >= 5 ? t.ops.arrived : stage >= 4 ? t.common.enRoute : t.ops.awaiting}</span></div>
    <section className={`${panel} overflow-hidden border-[hsl(var(--destructive)/.25)]`}><div className="flex flex-wrap items-center justify-between gap-3 bg-[hsl(var(--destructive)/.06)] p-5"><div className="flex items-center gap-3"><Ambulance size={22} className="text-[hsl(var(--destructive))]" /><div><h2 className="font-extrabold">{t.hospital.incoming}</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{stage >= 4 ? t.ops.localHandoff : t.ops.awaiting}</p></div></div><span className="rounded-full bg-[hsl(var(--destructive)/.1)] px-3 py-1 text-xs font-bold text-[hsl(var(--destructive))]">{t.common.critical}</span></div><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4">{[[t.hospital.patient, localize(demoPatient.name, lang)], [t.record.age, `${demoPatient.age} ${t.record.years}`], [t.record.bloodType, demoPatient.bloodType], [t.hospital.ambulanceId, 'AMB-204']].map(([label, value]) => <div key={label}><p className="text-xs text-[hsl(var(--muted-foreground))]">{label}</p><strong className="mt-1 block text-sm">{value}</strong></div>)}</div></section>
    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-5">
      <section className={`${panel} p-5`}><h2 className="font-extrabold">{t.hospital.profile}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[[t.record.patientName, localize(demoPatient.name, lang)], [t.record.patientId, demoPatient.patientId], [t.record.emergencyContact, localize(demoPatient.emergencyContact, lang)], [t.ops.destination, stage >= 3 ? localize(destination.name, lang) : t.ops.etaUnknown]].map(([label, value]) => <div key={label} className="rounded-xl bg-[hsl(var(--muted)/.65)] p-3"><div className="text-xs text-[hsl(var(--muted-foreground))]">{label}</div><strong className="mt-1 block text-sm">{value}</strong></div>)}</div></section>
      <section className={`${panel} p-5`}><h2 className="font-extrabold">{t.hospital.medical}</h2><div className="mt-4 flex gap-3 rounded-xl border border-[hsl(var(--destructive)/.3)] bg-[hsl(var(--destructive)/.07)] p-4 text-[hsl(var(--destructive))]"><AlertTriangle size={19} className="shrink-0" /><div><strong>{t.hospital.allergy}</strong><p className="mt-1 text-xs">{localize(demoPatient.allergyDetail, lang)}</p></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[hsl(var(--muted)/.6)] p-4"><h3 className="flex items-center gap-2 text-xs font-bold"><HeartPulse size={15} />{t.record.chronic}</h3>{demoPatient.chronic.map((item) => <p key={item.en} className="mt-2 text-sm">{localize(item, lang)}</p>)}</div><div className="rounded-xl bg-[hsl(var(--muted)/.6)] p-4"><h3 className="flex items-center gap-2 text-xs font-bold"><Pill size={15} />{t.record.medications}</h3>{demoPatient.medications.map((item) => <p key={item.en} className="mt-2 text-sm">{localize(item, lang)}</p>)}</div><div className="rounded-xl bg-[hsl(var(--muted)/.6)] p-4 sm:col-span-2"><h3 className="text-xs font-bold">{t.record.previous}</h3>{demoPatient.previous.map((item) => <p key={item.en} className="mt-2 text-sm">{localize(item, lang)}</p>)}</div></div></section>
      <section className={`${panel} p-5`}><h2 className="font-extrabold">{t.hospital.vitals}</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-3">{vitals.map(({ icon: Icon, label, value }) => <div key={label} className="rounded-xl bg-[hsl(var(--muted)/.65)] p-3"><Icon size={16} className="text-[hsl(var(--primary))]" /><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{label}</p><strong className="mt-1 block text-sm">{value}</strong></div>)}</div></section>
    </div><div className="space-y-5"><TransportTracker lang={lang} t={t} stage={stage} selectedHospital={selectedHospital} /><section className={`${panel} p-5`}><h2 className="font-extrabold">{t.hospital.etaTitle}</h2><p data-testid="text-hospital-destination" className="mt-4 text-lg font-extrabold">{stage >= 3 ? localize(destination.name, lang) : t.ops.etaUnknown}</p><p data-testid="text-hospital-eta" className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{stage >= 5 ? t.ops.arrived : stage >= 3 ? `${t.ops.eta}: ${destination.eta} ${t.common.minutes}` : t.ops.etaUnknown}</p><p className="mt-4 text-xs text-[hsl(var(--muted-foreground))]">{t.ops.routeValue}</p></section><section className={`${panel} p-5`}><div className="flex justify-between gap-3"><h2 className="font-extrabold">{t.hospital.readiness}</h2><span className="text-sm font-bold text-[hsl(var(--primary))]">{readiness}%</span></div><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{t.hospital.readinessCopy}</p><div className="mt-4 space-y-1">{t.hospital.checklist.map((item, index) => <button data-testid={`button-readiness-${index}`} type="button" key={item} onClick={() => onToggle(index)} className="flex w-full items-center gap-3 rounded-xl p-2 text-start text-xs hover:bg-[hsl(var(--muted)/.6)]"><span className={`grid size-6 shrink-0 place-items-center rounded-full ${checklist[index] ? 'bg-[hsl(var(--primary))] text-white' : 'border border-[hsl(var(--border))]'}`}>{checklist[index] && <Check size={14} />}</span>{item}</button>)}</div></section></div></div>
  </main>;
}